---
title: "Introduction to OS/161"
---
:sectnums:

== Introduction

[.lead]
ASST0 introduces you to the codebase and tools that you will be using
throughout the rest of the `ops-class.org` assignments.

It is unlikely that you have used OS/161 before, but some of the
other tools may be familiar to you:

* http://os161.eecs.harvard.edu[*OS/161*]: OS/161 includes both
. the sources of the the operating system you will be designing,
implementing, running and debugging, and
. a toolchain for cross compiling and running your kernel, including a
machine simulator called `sys161` footnote:[Also known as System/161].
* https://git-scm.com/[*Git*]: a fast distributed source control system that
tracks and saves your changes to OS/161 and enables effective collaboration.
* https://www.gnu.org/software/gdb/[*GDB*]: the GNU debugger, a powerful
debugging tool which will allow you to control and inspect your running
system.
  
=== Objectives

After completing ASST0 you should:

. Understand the source code structure of OS/161, the operating system you
will be modifying.
. Be familiar with Git, a fast distributed source control system, and GDB,
the GNU Debugger.
. Understand how `sys161` provides the hardware environment on which your
OS/161 kernel runs.
. Be comfortable reading the OS/161 source code and figuring out where and
how things are done.
. Be able to, modify, build and run an OS/161 kernel.

=== A Note on Cut-and-Paste

Another assignment objective is to get you up to speed working efficiently in
a Linux development environment using standard tools. Earlier versions of
this assignment had come to contain a lot of cut-and-paste snippets that
students could run from the command line.

While students found this helpful, we have decided to remove many of these
instructions and provide direction in English text instead. This is for the
simple reason that too many students were simply skimming the assignment text
while cutting and pasting the relevant sections into their terminal. (They
would even get annoyed when we had left out a step footnote:[Sometimes
intentionally...]&mdash;like changing into a different directory--and their
decision to blindly cut-and-paste from the assignment backfired.)

Unlike many of the things you will find online ASST0 is _not a tutorial._ You
will go slower, but you will learn a lot more from figuring out what to do if
we tell you:
____
Run the first OS/161 thread test and then shut down your kernel.
____
than if we tell you:
....
trinity@zion:~$ sys161 kernel "tt1;q"
....

Following these kinds of written and spoken instructions will also better
prepare you to interact with the course staff, who tend to give instructions
in English, not as executable terminal commands.

=== A Note on Learning Git

Another objective of this course is to help you learn to use common
development tools, particularly Git. However, like most programming tools the
best way to get started with and continue to learn Git is through the
extensive online documentation and multiple good online tutorials.

As a result, we have removed Git guides from the `ops-class.org`
documentation. Not only is any documentation we could provide much less
likely to be complete and up-to-date, but this will provide you with good
practice in online learning. Feel free to ask your course staff or other
students for help, either in person or using the online forum. Chances are
many of them use Git or something similar on a daily basis. When you become a
professional hacker, you will too.

Like anything else, learning Git takes practice and patience. But here's one
simple tip: *read Git commands outputs and error messages*. Git produces
incredibly useful output, particularly when an error occurs. Frequently the
output tells you _exactly_ what to do to address whatever issue you are
facing, down to the commands that you should type.

=== Collaboration Guidelines

ASST0 focuses on getting your environment set up and asking you to begin
familiarizing yourself with the OS/161 source you will be modifying. There is
a small amount of coding involved, but not too much. Here are the guidelines
for how to work together and work with your partner (if you have one):

TIP: Working side-by-side with your partner on ASST0 is *strongly
encouraged*.
  
TIP: Helping other students set up their `ops-class.org` environment is
encouraged.
    
TIP: Helping each other with Git is encouraged.
    
TIP: Discussing the code reading questions and browsing the source code with
other students is encouraged, *but students in separate groups should prepare
answers separately*.
    
WARNING: Dividing the code reading questions, scripting and development tasks
between partners is acceptable but discouraged.
  
CAUTION: Copying any answers from anyone who is not your partner or anywhere
else and submitting them as your own is cheating.
  
CAUTION: You may not refer to or incorporate any external sources without
explicit permission footnote:[Which you are extremely unlikely to get.].
  
== Choosing and Initializing Your Development Environment

[.lead]
Developing for OS/161 requires a specialized set of tools, including the
`sys161` simulator along with a GCC cross-compiler allowing you to create
MIPS r3000 binary executables that `sys161` can execute.

You have three options for how to access the OS/161 toolchain:

. Install the toolchain natively on your own Ubuntu machine
. Run a Ubuntu virtual machine that has the toolchain installed as a guest on
a Windows or Mac host
. Use a toolchain that has been preinstalled on a shared machine accessible
via SSH

Each option is described in more detail below. However, #1 requires access to
a computer running Ubuntu Linux, which you may or may not have. If you run
Mac or Windows, #2 or #3 are your best options. And if your course staff has
set up a shared machine for you, #3 is a very straightforward choice. That
said, there are other tradeoffs to each choice, so we suggest that you read
through your options carefully before making a decision.

=== Ubuntu Host

If you have a computer running Ubuntu Linux, we have packaged the OS/161
toolchain for the last two Ubuntu LTS releases (12.04 Precise and 14.04
Trusty) in a Launchpad PPA. Installation is simple:

....
sudo add-apt-repository ppa:geoffrey-challen/os161-toolchain
sudo apt-get update
sudo apt-get install os161-toolchain
....

If you don't have a computer running Linux, and you have a spare computer
around, you may want to give Ubuntu a try. Maintaining your own Linux machine
is a great way to learn more about system administration and, to some degree,
about operating systems as well.

=== Ubuntu Guest Using Vagrant

If you'd prefer to develop on your own machine but don't run Ubuntu Linux, we
have a Vagrant configuration allowing you to easily fire up a VirtualBox
guest virtual machine on your Windows or Mac host footnote:[We'll talk a lot
more about virtualization in class, but here's one example of how useful it
can be.].

The first step is to install https://www.vagrantup.com/[Vagrant], which
happliy comes with installers for most common operating systems. Next you
need to get our `Vagrantfile` which describes how to provision and configure
your virtual machine. You'll need Git installed to complete this next step.
Pick or create an empty directory to use for your OS/161 sources. Then clone
our Vagrant repository into that directory.

Once that's done, you should be able to run `vagrant up` from the directory
containing our `Vagrantfile`. Note that `vagrant up` will take a few minutes
to complete the first time, and you need to be online so that Vagrant can
download various external resources:

....
vagrant up # This may take a few minutes
....

Assuming `vagrant up` completes successfully, you should be able to log in to
your running virtual machine and run the OS/161 tools:

....
$ vagrant ssh
trinity@zion:~$ sys161
sys161: System/161 release 2.0.4, compiled Dec 23 2015 21:58:13
sys161: Usage: sys161 [sys161 options] kernel [kernel args...]
...
....

By default our configuration shares the `src` subdirectory of the directory
where you installed our `Vagrantfile` with the virtual machine, meaning that
you can edit your OS/161 source code either inside or outside of the virtual
machine. Given that by default our VM does not have a GUI, if you prefer a
graphical source code editor you may want to edit your code using tools
installed on the host. However, you need to be logged in to your VM to
compile and run your OS/161 kernel.

If you are having trouble, make sure that all Vagrant commands (`vagrant up`,
`vagrant ssh`, etc.) are run from the same directory as the `Vagrantfile` you
created previously. That's just how Vagrant works.

=== Preexisting External Installation

You may have access to a shared machine with the OS/161 toolchain installed,
allowing you to work remotely over SSH. While this is by far the easiest
option, it does limit your ability to work offline and may affect your choice
of source code editor.
 
=== Do-It-Yourself Installation on Other Flavors of UNIX

We don't support this option, but if you'd like to try instructions are
available at the http://os161.eecs.harvard.edu[OS/161 website]. You will need
to download, configure, compile and install from the OS/161 toolchain
sources. Linux and other UNIX variants are likely to work. Superheroes and
the overly determined have gotten things to work on OSX. Please use the most
recent version of the cross-compilation toolchain and System/161.

== Configuring, Building, and Running on OS/161 Kernel

[.lead]
Now that you have your development environment ready, on to the fun stuff:
booting your first OS/161 kernel.

=== Download the OS/161 Source Code

We distribute the OS/161 source code using Git. Starting with a clone of our
repository makes it easy for us to distribute updates, bug fixes, and new
OS/161 releases, which can be merged easily into your development repository.

First, choose a directory to work in:

* If you are using our Vagrant virtual machine,
you can run Git either inside or outside of your virtual machine, assuming
your host machine has Git installed. For simplicity, we suggest cloning the
sources inside your virtual machine in `/home/trinity/src`, which should
exist and be an empty directory.
* If you have the toolchain installed natively you can create your source
directory wherever you want.

Let's say you've chosen a directory called `src`, which should either not
exist or (in the case of the Vagrant VM) be empty. Clone
https://gitlab.ops-class.org/staff/os161[our `ops-class.org` Git repository]
into that directory.

=== Configure Your OS/161 Source Tree

The next step is to configure the OS/161 sources by running the `configure`
command located at the root of your source tree. You need to do this (very
short) step only when you completely remove your source tree for some reason.
The only configuration step is to set up where various binaries--including
system executable and your kernel--will be created when you run `make` in
later steps. Run `configure -help` to find out more including available
command line options.

Note that by default OS/161 installs things to `$HOME/os161/root`, which is a
fine plan to put things if you are working on a shared machine. For our
dedicated VM we use `$HOME/root` to shorten the directory paths a bit, but
this requires that you use the `--ostree` argument to `configure`. If you
forget this argument either now or when you need to rerun `configure` later,
you will install things into `$HOME/os161/root`. *This has caused confusion
for some students previously, so please be careful.*

=== Configure Your OS/161 Kernel

The kernel sources for OS/161 are in the `kern` subdirectory, which has its
own configuration script. Change into `kern/conf` and look around. You should
notice a configuration script, a base configuration file (`kern.conf`), and
four configurations that include `kern.conf`.

You should take a look at `kern.conf` and one of the configurations to get a
sense of the format. But for now, the only thing we're concerned about is
ensuring that we enable `dumbvm` for `ASST0`. You're going to write a
full-fledged virtual memory (VM) system in `ASST3`, but for the first few
assignments `dumbvm` provides enough of a "dumb" VM to allow you to proceed.
Configure a kernel now with `dumbvm` enabled.

The OS/161 kernel configuration process sets various options that control how
your kernel gets built, so unlike the configuration step above you will
probably need to modify these files at some point during later assignments.
In particular, `conf.kern` determines what source files get included in your
kernel build, so if you add sources to the kernel you'll need to add them to
`conf.kern` as well.
