---
title: "Build Your Own OS"
omitTop: true
spelling_exceptions:
  - Facebook
  - Mark Zuckerberg
description: >
  Programming assignents are the heart of the ops-class.org experience. The
  most effective way to learn operating system concepts is to build one
  yourself.
priority: 0.9
changefreq: monthly
---

[.lead]
//
The best way to learn about operating systems is to implement one.
//
So programming assignments are the heart of {ops-class}.

{ops-class} assignments use the excellent {os161} instructional operating
system.
//
{os161} was developed at Harvard University by
//
http://www.hcs.harvard.edu/~dholland/[David Holland],
//
https://www.eecs.harvard.edu/margo/[Margo Seltzer], and
//
https://github.com/ops-class/os161/blob/master/CHANGES[others].
//
It provides some of the realism of large operating systems like
https://www.linux.com[Linux].
//
But it remains compact enough to give you a chance to implement large OS
subsystems&mdash;like link:/asst/3/[virtual memory]&mdash;yourself.
//
http://dl.acm.org/citation.cfm?id=563383[This paper] provides a good
overview of OS/161.

The assignments also provide a variety of different programming challenges.
//
{asst1} is just a warmup.
//
{asst2} challenges you to connect two existing interfaces.
//
{asst3} provides the opportunity to implement a large piece of functionality
and design several internal interfaces.
//
These challenges are similar to those that you will face in industry or when
building large software systems.
//
And all the assignments require understanding a large and complex code base.

////
and {asst4} requires you to make a small set of important changes to an
existing (file)system.
////

If that wasn't exciting enough, these assignments are the _same ones_ that
kept https://en.wikipedia.org/wiki/Mark_Zuckerberg[Mark Zuckerberg]
https://www.youtube.com/watch?v=-3Rt2_9d7Jg[busy in his last semester at
Harvard]&mdash;while he was starting https://www.facebook.com[Facebook].
//
Many students at multiple institutions have benefited from their struggle
with {os161}.
//
We think you will too.

We provide a bit more detail about each assignment below.

== {asst0}

This first assignment introduces you to the programming environment you will
be working in this semester: the OS/161 operating system, the `sys161`
simulator, the GNU debugger (GDB), and the Git revision control system.

== {asst1}

Your first real taste of kernel programming.
//
Implement critical kernel synchronization primitives&mdash;locks, condition
variables and reader-writer locks.
//
Next, use them to solve a few simple toy synchronization problems.

== {asst2}

The first big and complex assignment.
//
Implement the system call interface.
//
When you are finished, your kernel can run user programs.

== {asst3}

The mountain top.
//
A large amount of code to implement and several internal interfaces to
design.
//
Implement virtual memory, including address translation, TLB management, page
replacement and swapping.
//
When you are done, your kernel can run forever without running out of memory.

////
== {asst4}
////

// vim: ts=2:sw=2:et
