---
title: "<code>test161</code>: The OS/161 Testing Tool"
spelling_exceptions:
  - PPA
  - YAML
  - GVM
---
:sectnums:

== Introduction

[.lead]
`test161` is the OS/161 testing tool designed and implemented by
https://blue.cse.buffalo.edu/people/shaseley/[Scott Haseley] and
https://blue.cse.buffalo.edu/people/ychen78/[Yihong Chen]. It will both allow
you test your assignments locally and submit them our testing server for
official evaluation.

Below we through how to install, configure, and run `test161`. While the
specific testing target will change from assignment to assignment, we use
link:/asst/1/[ASST1] below as an example. Note that this tutorial duplicates
some information from the official `test161`
https://github.com/ops-class/test161/blob/master/README.adoc[README] located
on the project's https://github.com/ops-class/test161[GitHub page].

=== Installation

Eventually `test161` will be distributed as part of the OS/161 toolchain,
allowing you to install it from the
https://launchpad.net/~geoffrey-challen/+archive/ubuntu/os161-toolchain/[`ops-class.org`
Launchpad PPA]. However, at the moment the installation is a bit more
complicated.

==== Installing Go

`test161` is written in https://golang.org/[Go] footnote:[Which is awesome.
https://tour.golang.org/[Learn it!]]. So to install `test161` you must first
install Go. Unfortunately, most Linux distributions package a fairly
out-of-date version of Go. However, Go has binary distributions prepared for
https://golang.org/dl/[most programming environments]. *But
keep in mind that you need to install `test161` in the same environment where
you compile and run your OS/161 kernel.* So you should install Go there as
well.

An excellent alternative to Go's https://golang.org/dl/[official packages]
is https://github.com/moovweb/gvm[GVM, the Go Version Manager]. We encourage
you to use this excellent tool. GVM is very easy to install on the Ubuntu
systems that we have packaged the OS/161 toolchain for:

[source,bash]
----
sudo apt-get install -y curl bison # Install installation requirements
bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
source $HOME/.gvm/scripts/gvm
----

At this point you are ready to start using GVM. We are currently building and
testing `test161` with Go version `go1.6beta2`. However, because the Go
compiler is now written in Go, installing versions of Go past 1.5 require
installing Go version 1.4 first.

[source,bash]
----
gvm install go1.4
gvm use 1.4
gvm install go1.6beta2
gvm use 1.6beta2 --default
----

Once you have installed Go 1.6 you can remove Go 1.4 if you like:

[source,bash]
----
gvm uninstall go1.4
----

==== Setting your `GOPATH`

Note that `gvm` will set your `GOPATH` and `PATH` variables properly to allow
you to run Go binaries that you install. However, if you did not use GVM or
are interested in writing Go code you should set a more accessible `GOPATH`
as described as https://golang.org/doc/code.html#GOPATH[described here.] If
you do not set your `GOPATH` environment variable correctly the following
steps will fail. And if you do not set your `PATH` environment variable to
include the directory where Go installs binaries you will not be able to run
`test161` from your path.

=== Installing `test161`

Once you have Go installed, upgrading or installing `test161` is simple:

[source,bash]
----
go get -u github.com/ops-class/test161/test161
----

If this completes successfully, and if have set your `GOPATH` and `PATH`
variables properly as described above, you will we able to run `test161`:

[source,bash]
----
$ test161

    usage: test161  <command> <flags> <args>

           test161 run [-dry-run | -r] [sequential | -s] [-dependencies | -d]
                       [-verbose | -v (whisper|quiet|loud*)] [-tag] <names>
...
----

=== Configuration

`test161` requires a configuration file to operate. If you run `test161 run`
it will get you started with some example values. You can create your
`.test161.conf` file either in your home directory--which is probably best
for most users--or in your OS/161 root directory where you run `test161`.

For local testing your configuration file only needs to tell `test161` where
to find your OS/161 root directory and where to find the `test161`
target, test, and command files. Here's an example that works in the OS/161
Vagrant VM that we provide:

[source,bash]
----
rootdir: /home/trinity/root/
test161dir: /home/trinity/src/test161/
----

We'll add more values to the `.test161.conf` file later when we set up
`test161` to submit your assignment for grading.

*Note that the `test161.conf` file is in http://yaml.org/[YAML] syntax and
that YAML doesn't like tabs.* You may want to disable tab expansion when
editing your `.test161.conf` file if your normal editor performs it.

== Running `test161` Targets

[.lead]
`test161` is a very flexible tool and can rapidly run one or many tests and
evaluate their output.

For this example, we'll assume that you want to run all tests for ASST1 and
perform grading. To do that, you provide the `asst1` target as the argument
to `test161 run`. Here's what happens when we run it on the base sources
downloaded from the https://github.com/ops-class/os161[`ops-class.org` OS/161
GitHub repository]:

[source,role='noautohighlight']
----
$ test161 run asst1
0.000000	sys161: System/161 release 2.0.6, compiled Feb 16 2016 01:44:26
0.014289
0.014289	OS/161 base system version 2.0.1
0.014289	Copyright (c) 2000, 2001-2005, 2008-2011, 2013, 2014
0.014289	   President and Fellows of Harvard College.  All rights reserved.
0.236243
0.236243	Put-your-group-name-here's system version 0 (ASST1 #2)
0.266461
0.266461	756k physical memory available
0.286483	Device probe...
0.286483	lamebus0 (system main bus)
...
2.965587	Operation took 0.018019320 seconds
2.991262	OS/161 kernel [? for menu]:
2.849897	OS/161 kernel [? for menu]:
2.844126	OS/161 kernel [? for menu]:
3.026152	cvt3: Should panic...
3.036162	cvt3: FAIL
3.046057	OS/161 kernel [? for menu]:
3.036162	Operation took 0.053904920 seconds
3.076270	OS/161 kernel [? for menu]:
2.914384	lt1: FAIL
2.914384	Operation took 0.087485440 seconds
2.934525	OS/161 kernel [? for menu]:
Test                             Result       Score
------------------------------   ----------   ----------
boot.t                           correct      0/0
sync/rwt5.t                      incorrect    0/1
sync/rwt4.t                      incorrect    0/1
sync/rwt3.t                      incorrect    0/1
sync/cvt4.t                      incorrect    0/1
sync/rwt1.t                      incorrect    0/5
sync/rwt2.t                      incorrect    0/2
sync/lt2.t                       incorrect    0/1
sync/lt3.t                       incorrect    0/1
sync/cvt3.t                      incorrect    0/1
sync/lt1.t                       incorrect    0/8
sync/cvt1.t                      skip         0/4
syncprobs/sp2.t                  skip         0/10
sync/cvt2.t                      skip         0/4
syncprobs/sp1.t                  skip         0/10

Total Correct  : 1/15
Total Incorrect: 10/15
Total Aborted  : 4/15

Total Score    : 0/50
----

As you can see, `test161` has rapidly generated a lot of useful output while
also giving our base sources the score they deserve on link:/asst/1[ASST1]:
0/50! Let's quickly go through the two mains parts of the `test161` output.

=== `sys161` Output

To speed execution, `test161` runs multiple tests in parallel. As a result,
test output is interleaved at parts of the testing suite where multiple tests
are being run. At the beginning of the ASST1 test suite only the boot test is
being performed because all other tests depend on it, so the output is not
interleaved. However, at the end several tests are being run in parallel and
so the output is interleaved.

This can be difficult to interpret, so `test161 run` provides a `-s` option.
This does not effect parallel testing, which `test161` will still perform
when the dependency graph allows it. However, it does make the output
sequential and easier to read.

=== Test Status

Following the test output `test161` prints a summary detailing what tests
were performed and, if appropriate, how they were scored. Scoring is optional
and only performed when using certain targets.

In the example above, the output shows that `boot.t` ran correctly but earned
no points. That is because the kernel booted but this was not worth any
points for ASST1. However, if the kernel had not booted the rest of the tests
would have been skipped. In this case, `boot.t` was run because it was
specified as a _dependency_ by other tests that were included as part of the
ASST1 target. `test161` can automatically run test dependencies when
appropriate.

For the next 10 tests above `test161` reports that they did not complete
correctly. Again, this is unsurprising given that the base OS/161 sources do
not include working locks, condition variables, or reader-writer locks. As
you complete portions of each assignment you will notice that your score will
increase.

For the final 4 tests `test161` reports them as being skipped. This was
because their dependencies were not met. For example, the condition-variable
tests `cvt{1,2}` depend on working locks, and these locks did not work.
Similarly, both the stoplight and whale mating synchronization test drivers
rely on working locks.

=== Running Single `test161` Tests

In our example above `test161` was used to run a _target_, which configures a
set of tests to be run and maps test results to point values. If you are
curious, look at the `asst1.tt` file located in the `test161` subdirectory of
your OS/161 source tree. (Or wherever you configured your `test161dir` in
`.test161.conf`.)

But `test161` can also be a part of your development process by running
single tests and reporting their output (without scores). Here is an example,
again with the base OS/161 sources:

[source,role='noautohighlight']
----
$ test161 run sync/sem1.t
0.000000	sys161: System/161 release 2.0.6, compiled Feb 16 2016 01:44:26
0.000000
0.000000	OS/161 base system version 2.0.1
0.018289	Copyright (c) 2000, 2001-2005, 2008-2011, 2013, 2014
0.018289	   President and Fellows of Harvard College.  All rights reserved.
0.228843
0.228843	Put-your-group-name-here's system version 0 (ASST1 #2)
....
3.917044	sys161:   cpu7: 739019 kern, 0 user, 39921249 idle; 354 ll, 346/8
sc, 895 sync
3.917044	sys161: 8673 irqs 0 exns 0r/0w disk 7r/5548w console 0r/0w/1m emufs
0r/0w net
3.917044	sys161: Elapsed real time: 1.608594 seconds (86.582 mhz)
3.917044	sys161: Elapsed virtual time: 3.919384560 seconds (25 mhz)

Test                             Result
------------------------------   ----------
sync/sem1.t                      correct

Total Correct  : 1/1
----

In this case we ran the semaphore test `sem1`, which does work in the base
sources, and `test161` produced output reflecting that. You can also tell
`test161` to run both a test and its dependencies by providing the `-d` flag
to `test161 run`. The output of `test161 run -d sync/sem1.t` will show that
both `sem1` and it's dependency (`boot.t`) were run.

=== Running Groups of Tests

The name passed to `test161 run` identifies a test relative to the `tests`
subdirectory of the the `test161dir` configured in `.test161.conf`. In this
case, `/home/trinity/src/test161/tests/sync/sem1.t` contains:

[source,yaml]
----
---
name: "Semaphore Test"
tags:
  - sync
  - semaphore
depends:
  - boot
---
sem1
----
You'll notice that the `sem1` test also belongs to two groups: `sync` and
`semaphore`. Groups provide another useful way to run `test161`:

[source,role='noautohighlight']
----
$ test161 run sync
...
Test                             Result
------------------------------   ----------
sync/rwt3.t                      incorrect
sync/lt2.t                       incorrect
sync/rwt4.t                      incorrect
sync/rwt5.t                      incorrect
sync/cvt3.t                      incorrect
sync/lt3.t                       incorrect
sync/cvt4.t                      incorrect
sync/rwt2.t                      incorrect
sync/lt1.t                       incorrect
sync/rwt1.t                      incorrect
sync/cvt1.t                      incorrect
sync/sem1.t                      correct
sync/cvt2.t                      incorrect

Total Correct  : 1/13
Total Incorrect: 12/13
----

Here we've asked `test161` to run all of the tests that are in the `sync`
group. Note that, unlike the `asst1` target, in this case dependencies were
not requested and so `cvt{1,2}` were run even though the lock tests failed.
To respect test dependencies provide `test161` with the `-d` flag.

== Submitting Using `test161`

We will provide more information about using `test161` to submit your
`ops-class.org` assignments once the submission server is ready.
