---
title: "<code>test161</code>: The OS/161 Testing Tool"
spelling_exceptions:
  - PPA
  - YAML
  - GVM
---
:sectnums:

== Introduction

[.lead]
`test161` is the OS/161 testing tool designed and implemented by
https://blue.cse.buffalo.edu/people/shaseley/[Scott Haseley] and
https://blue.cse.buffalo.edu/people/ychen78/[Yihong Chen]. It will both allow
you test your assignments locally and submit them our testing server for
official evaluation.

Below we run through how to install, configure, run, and use `test161`. While
the specific testing target will change from assignment to assignment, we use
link:/asst/1/[ASST1] below as an example. Note that this tutorial duplicates
some information from the official `test161`
https://github.com/ops-class/test161/blob/master/README.adoc[README] located
on the project's https://github.com/ops-class/test161[GitHub page].

=== Installation

++++
<div class="embed-responsive embed-responsive-16by9"
		 style="margin-top:10px; margin-bottom:10px; border:1px solid grey">
<div class="youtube-container" data-id="riGAGJx9tnw"></div>
</div>
++++

Eventually `test161` will be distributed as part of the OS/161 toolchain,
allowing you to install it from the
https://launchpad.net/~geoffrey-challen/+archive/ubuntu/os161-toolchain/[`ops-class.org`
Launchpad PPA]. However, at the moment the installation is a bit more
complicated.

==== Installing Go

`test161` is written in https://golang.org/[Go] footnote:[Which is awesome.
https://tour.golang.org/[Learn it!]]. So to install `test161` you must first
install Go.

Unfortunately, most Linux distributions package a fairly out-of-date version
of Go. However, Go has binary distributions prepared for
https://golang.org/dl/[most programming environments]. *But keep in mind that
you need to install `test161` in the same environment where you compile and
run your OS/161 kernel.* So you should install Go there as well. Another
option is to install Go from
https://launchpad.net/~ubuntu-lxc/+archive/ubuntu/lxd-stable[this PPA] that
maintains a more up-to-date version.

Probably the best alternative https://github.com/moovweb/gvm[GVM, the Go
Version Manager], which can download, build, install, and manage multiple Go
versions for you. We encourage you to use this excellent tool. GVM is very
easy to install on the Ubuntu systems that we have packaged the OS/161
toolchain for:

[source,role='noautohighlight']
----
sudo apt-get install -y curl bison # Install installation requirements
bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
source $HOME/.gvm/scripts/gvm
----

At this point you are ready to start using GVM. We are currently building and
testing `test161` with Go version `go1.5.3`. However, because the Go
compiler is now written in Go, installing versions of Go past 1.5 require
installing Go version 1.4 first.

[source,role='noautohighlight']
----
gvm install go1.4
gvm use 1.4
gvm install go1.5.3
gvm use 1.5.3 --default
----

Once you have installed Go 1.6 you can remove Go 1.4 if you like:

[source,role='noautohighlight']
----
gvm uninstall go1.4
----

==== Setting your `GOPATH`

Note that `gvm` will set your `GOPATH` and `PATH` variables properly to allow
you to run Go binaries that you install. However, if you did not use GVM or
are interested in writing Go code you should set a more accessible `GOPATH`
as described as https://golang.org/doc/code.html#GOPATH[described here.] If
you do not set your `GOPATH` environment variable correctly the following
steps will fail. And if you do not set your `PATH` environment variable to
include the directory where Go installs binaries you will not be able to run
`test161` from your path.

=== Installing `test161`

Once you have Go installed, upgrading or installing `test161` is simple:

[source,role='noautohighlight']
----
go get -u github.com/ops-class/test161/test161
----

If this completes successfully, and if have set your `GOPATH` and `PATH`
variables properly as described above, you will we able to run `test161`:

[source,role='noautohighlight']
----
$ test161

    usage: test161  <command> <flags> <args>

           test161 run [-dry-run | -r] [sequential | -s] [-dependencies | -d]
                       [-verbose | -v (whisper|quiet|loud*)] [-tag] <names>
...
----

=== Configuration

`test161` requires a configuration file to operate. You can create your
`.test161.conf` file either in your home directory--which is probably best
for most users--or in your OS/161 root directory where you run `test161`.

If you run `test161 run` without a configuration file an example will be
displayed on screen. You can save this output as `~/.test161.conf` and edit
it appropriately. For local testing your configuration file only needs to
tell `test161` where to find your OS/161 root directory and where to find the
`test161` target, test, and command files. Here's an example that works in
the OS/161 Vagrant VM that we provide:

[source,role='noautohighlight']
----
rootdir: /home/trinity/root/
test161dir: /home/trinity/src/test161/
----

We'll add more values to the `.test161.conf` file later when we set up
`test161` to submit your assignment for grading.

*Note that the `test161.conf` file is in http://yaml.org/[YAML] syntax and
that YAML doesn't like tabs.* You may want to disable tab expansion when
editing your `.test161.conf` file if your normal editor performs it.

== Running `test161` Targets

++++
<div class="embed-responsive embed-responsive-16by9"
		 style="margin-top:10px; margin-bottom:10px; border:1px solid grey">
<div class="youtube-container" data-id="rPVtuUz1w5I"></div>
</div>
++++

[.lead]
`test161` is a very flexible tool and can rapidly run one or many tests and
evaluate their output.

For this example, we'll assume that you want to run all tests for ASST1 and
perform grading. To do that, you provide the `asst1` target as the argument
to `test161 run`. Here's what happens when we run it on the base sources
downloaded from the https://github.com/ops-class/os161[`ops-class.org` OS/161
GitHub repository]:

[source,role='noautohighlight']
----
$ test161 run asst1
0.000000	sys161: System/161 release 2.0.6, compiled Feb 16 2016 01:44:26
0.014289
0.014289	OS/161 base system version 2.0.1
0.014289	Copyright (c) 2000, 2001-2005, 2008-2011, 2013, 2014
0.014289	   President and Fellows of Harvard College.  All rights reserved.
0.236243
0.236243	Put-your-group-name-here's system version 0 (ASST1 #2)
0.266461
0.266461	756k physical memory available
0.286483	Device probe...
0.286483	lamebus0 (system main bus)
...
2.965587	Operation took 0.018019320 seconds
2.991262	OS/161 kernel [? for menu]:
2.849897	OS/161 kernel [? for menu]:
2.844126	OS/161 kernel [? for menu]:
3.026152	cvt3: Should panic...
3.036162	cvt3: FAIL
3.046057	OS/161 kernel [? for menu]:
3.036162	Operation took 0.053904920 seconds
3.076270	OS/161 kernel [? for menu]:
2.914384	lt1: FAIL
2.914384	Operation took 0.087485440 seconds
2.934525	OS/161 kernel [? for menu]:
Test                             Result       Score
------------------------------   ----------   ----------
boot.t                           correct      0/0
sync/rwt5.t                      incorrect    0/1
sync/rwt4.t                      incorrect    0/1
sync/rwt3.t                      incorrect    0/1
sync/cvt4.t                      incorrect    0/1
sync/rwt1.t                      incorrect    0/5
sync/rwt2.t                      incorrect    0/2
sync/lt2.t                       incorrect    0/1
sync/lt3.t                       incorrect    0/1
sync/cvt3.t                      incorrect    0/1
sync/lt1.t                       incorrect    0/8
sync/cvt1.t                      skip         0/4
syncprobs/sp2.t                  skip         0/10
sync/cvt2.t                      skip         0/4
syncprobs/sp1.t                  skip         0/10

Total Correct  : 1/15
Total Incorrect: 10/15
Total Aborted  : 4/15

Total Score    : 0/50
----

As you can see, `test161` has rapidly generated a lot of useful output while
also giving our base sources the score they deserve on link:/asst/1[ASST1]:
0/50! Let's quickly go through the two mains parts of the `test161` output.

=== `sys161` Output

To speed execution, `test161` runs multiple tests in parallel. As a result,
test output is interleaved at parts of the testing suite where multiple tests
are being run. At the beginning of the ASST1 test suite only the boot test is
being performed because all other tests depend on it, so the output is not
interleaved. However, at the end several tests are being run in parallel and
so the output is interleaved.

This can be difficult to interpret, so `test161 run` provides a `-s` option.
This does not effect parallel testing, which `test161` will still perform
when the dependency graph allows it. However, it does make the output
sequential and easier to read.

=== Test Status

Following the test output `test161` prints a summary detailing what tests
were performed and, if appropriate, how they were scored. Scoring is optional
and only performed when using certain targets.

In the example above, the output shows that `boot.t` ran correctly but earned
no points. That is because the kernel booted but this was not worth any
points for ASST1. However, if the kernel had not booted the rest of the tests
would have been skipped. In this case, `boot.t` was run because it was
specified as a _dependency_ by other tests that were included as part of the
ASST1 target. `test161` can automatically run test dependencies when
appropriate.

For the next 10 tests above `test161` reports that they did not complete
correctly. Again, this is unsurprising given that the base OS/161 sources do
not include working locks, condition variables, or reader-writer locks. As
you complete portions of each assignment you will notice that your score will
increase.

For the final 4 tests `test161` reports them as being skipped. This was
because their dependencies were not met. For example, the condition-variable
tests `cvt{1,2}` depend on working locks, and these locks did not work.
Similarly, both the stoplight and whale mating synchronization test drivers
rely on working locks.

=== Running Single `test161` Tests

In our example above `test161` was used to run a _target_, which configures a
set of tests to be run and maps test results to point values. If you are
curious, look at the `asst1.tt` file located in the `test161` subdirectory of
your OS/161 source tree. (Or wherever you configured your `test161dir` in
`.test161.conf`.)

But `test161` can also be a part of your development process by running
single tests and reporting their output (without scores). Here is an example,
again with the base OS/161 sources:

[source,role='noautohighlight']
----
$ test161 run sync/sem1.t
0.000000	sys161: System/161 release 2.0.6, compiled Feb 16 2016 01:44:26
0.000000
0.000000	OS/161 base system version 2.0.1
0.018289	Copyright (c) 2000, 2001-2005, 2008-2011, 2013, 2014
0.018289	   President and Fellows of Harvard College.  All rights reserved.
0.228843
0.228843	Put-your-group-name-here's system version 0 (ASST1 #2)
....
3.917044	sys161:   cpu7: 739019 kern, 0 user, 39921249 idle; 354 ll, 346/8
sc, 895 sync
3.917044	sys161: 8673 irqs 0 exns 0r/0w disk 7r/5548w console 0r/0w/1m emufs
0r/0w net
3.917044	sys161: Elapsed real time: 1.608594 seconds (86.582 mhz)
3.917044	sys161: Elapsed virtual time: 3.919384560 seconds (25 mhz)

Test                             Result
------------------------------   ----------
sync/sem1.t                      correct

Total Correct  : 1/1
----

In this case we ran the semaphore test `sem1`, which does work in the base
sources, and `test161` produced output reflecting that. You can also tell
`test161` to run both a test and its dependencies by providing the `-d` flag
to `test161 run`. The output of `test161 run -d sync/sem1.t` will show that
both `sem1` and it's dependency (`boot.t`) were run.

=== Running Groups of Tests

The name passed to `test161 run` identifies a test relative to the `tests`
subdirectory of the the `test161dir` configured in `.test161.conf`. In this
case, [.small]`~/src/test161/tests/sync/sem1.t` contains:

[source,yaml]
----
---
name: "Semaphore Test"
tags:
  - sync
  - semaphore
depends:
  - boot
---
sem1
----
You'll notice that the `sem1` test also belongs to two groups: `sync` and
`semaphore`. Groups provide another useful way to run `test161`:

[source,role='noautohighlight']
----
$ test161 run sync
...
Test                             Result
------------------------------   ----------
sync/rwt3.t                      incorrect
sync/lt2.t                       incorrect
sync/rwt4.t                      incorrect
sync/rwt5.t                      incorrect
sync/cvt3.t                      incorrect
sync/lt3.t                       incorrect
sync/cvt4.t                      incorrect
sync/rwt2.t                      incorrect
sync/lt1.t                       incorrect
sync/rwt1.t                      incorrect
sync/cvt1.t                      incorrect
sync/sem1.t                      correct
sync/cvt2.t                      incorrect

Total Correct  : 1/13
Total Incorrect: 12/13
----

Here we've asked `test161` to run all of the tests that are in the `sync`
group. Note that, unlike the `asst1` target, in this case dependencies were
not requested and so `cvt{1,2}` were run even though the lock tests failed.
To respect test dependencies provide `test161` with the `-d` flag.

== Submitting Using `test161`

[.lead]
Once you are happy with your score on each assignment footnote:[Or with the
deadline looming...], `test161` allows you to submit your assignments for
automated grading.

With some important exceptions (see below), remote `test161` grading is
identical to the tests that you run in your local environment. As a result,
the grade or performance marks that you achieve on the remote server should
line up closely with what you achieve locally.

This also means that it is both unnecessary and discouraged to repeatedly
submit assignments using `test161`. You will notice that the remote output
from `test161` is different than what you normally see, and that many useful
messages are disabled. This is because remote automated testing is not
intended to produce diagnostic output. Iterative `test161` testing should be
done locally. If you are missing tests required to evaluate your kernel, that
is because writing them is part of the assignment. So do that, rather than
bang on the `test161` server.

=== Preparing for Submission

++++
<div class="embed-responsive embed-responsive-16by9"
		 style="margin-top:10px; margin-bottom:10px; border:1px solid grey">
<div class="youtube-container" data-id="wzS-moehW0I"></div>
</div>
++++

To submit to https://test161.ops-class.org[`test161.ops-class.org`], you
first need to retrieve your user token and public key and configure your
repository to allow `test161` to clone it during remote testing.

Log in to https://test161.ops-class.org[`test161.ops-class.org`] and click on
the profile tab. You should see a submit token, which you will need to add to
your `.test161.conf` file in a minute.

You should also see a dialog allowing you to create a new public key. The
reason for this is that `test161` needs access to your Git repository to test
it but will _not_ test public repositories. So you need to ensure that
`test161` can clone the OS/161 repository that you are going to submit with
the public key that is shown on your profile page.

How to add this key differs depending on where you host your private OS/161
Git repository. GitHub allows you to set up
https://developer.github.com/guides/managing-deploy-keys/[read-only deploy
keys], as does http://doc.gitlab.com/ce/ssh/README.html[GitLab]. *You should
not add this key to your Git user account or give it push access to your
OS/161 or any other repository.* If you are hosting your Git repository
somewhere that does not support deployment keys, we would suggest finding an
alternative that does.

=== Configuration for Submission

To submit assignments we have to add a few new values to your `.test161.conf`
file, wherever you put it. Here's what we started with above and what was
sufficient for local testing:

[source,role='noautohighlight']
----
rootdir: /home/trinity/root/
test161dir: /home/trinity/src/test161/
----

For remote submission you to add values that tell `test161` where to submit
your assignment, how to get your code, and who you are working with. Here's
an example:

[source,role='noautohighlight']
----
rootdir: /home/trinity/root/
test161dir: /home/trinity/src/test161/
server: https://test161.ops-class.org
repository: git@gitlab.ops-class.org:staff/os161.git
users:
  - email: "challen@buffalo.edu"
    token: "MYSECRETTOKEN"
  - email: "mypartner@buffalo.edu"
    token: "HERSECRETTOKEN"
----

The `token` value is the token that is shown on your
https://test161.ops-class.org[`test161.ops-class.org`] profile page. If you
are working with a partner you should add their email address and token as
shown above. Contact them privately to get their token. If you are working
alone only submit on behalf of yourself.

At any point you can use the
https://test161.ops-class.org[`test161.ops-class.org`] web interface to
regenerate a new public key or private token. This is particularly important
if you end a partnership to ensure that your partner can no longer submit on
your behalf.

=== Submitting Your Assignment

++++
<div class="embed-responsive embed-responsive-16by9"
		 style="margin-top:10px; margin-bottom:10px; border:1px solid grey">
<div class="youtube-container" data-id="5i1_C-w46HA"></div>
</div>
++++

If you have followed the instructions above then you are ready to submit your
assignment. But before you do, *please test locally using `test161 run`*. Our
server is not intended to be part of your testing and development
process--that's why we provided a local client and grading approximations.

That said, _please submit early and often_ once you have code that you are
somewhat happy with. It is better to submit a few hours beforehand and lock
in partial credit than wait until the minutes before the deadline when you
might not receive any points.

Once you are happy with the score that you earned using `test161 run`, there
are a few other things you need to do before submitting. First, make sure
that all of your changes are checked in and that the tip of the branch that
you are working on has the changes that you want to submit. Second, make sure
that the changes are pushed to the remote repository you configured in your
`.test161.conf` file.

The best way to check for this is to run `git status`. This is bad output,
and indicates that you need to commit your changes:
[source,bash]
----
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
...
----

This is also bad output and indicates that you need to push your changes to
your remote:
[source,bash]
----
$ git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
----

This is what you want to see:
[source,bash]
----
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
----

The next thing to ensure is that you've earned some points on the assignment.
`test161` will not allow you to submit code that earns a zero. Use `test161
run` to determine this.

At that point you should be ready to submit. You need to run the `test161
submit <target>` command from your Git source directory. When you do, the
following steps will take place locally:

. `test161` will clone a copy of the Git repository in your `.test161.conf`
file into a temporary directory and check out the commit that you are
submitting. This can fail if you have not pushed your changes.

. `test161` will then configure and build your kernel. This can fail or
produce incorrect results if you have uncommitted changes in your working
tree.

. `test161` will then run and the kernel that it built by running `test161
run <target>`. If you have not earned any points you will not be able to
submit. If you have earned some points, `test161` will ask you to confirm
your submission and agree to the course collaboration policy before
submitting. This is mandatory.

At that point the action moves to the
https://test161.ops-class.org[`test161.ops-class.org`] server. You can watch
the live testing process if you are logged in and have all or that submission
target selected. The server-side testing process is fundamentally no
different than the local testing process, with a few caveats described below.
Hopefully, when testing completes you have earned the score that you were
expecting.

Note that testing and grading may not happen immediately. If the `test161`
server receives many requests the process will slow down and future
submissions will be delayed. *Keep this in mind when submitting close to the
deadline!* Your submission will be timestamped when the request arrives on
our server, but you may not be able to see the testing results until after
the deadline has passed.

Congrats! You submitted your assignment.

==== Troubleshooting

Here is a list of things to try if your submission is not succeeding, either
locally or remotely:

. Try updating your copy of `test161` by running `go get -u
github.com/ops-class/test161/test161`. This is always safe to do.

. Make sure that all of your changes are checked in and pushed to your
remote repository.

. If you have configured a remote in your `.test161.conf` file, make sure it
matches the one that you are pushing and pulling from.

. Make sure that the https://test161.ops-class.org[`test161.ops-class.org`]
server can use the public key that you have configured through the web
interface to pull from the repository that you are submitting.

Here is a list of things to try if you are not getting as much credit as you
deserve:

. If the assignment required you to write certain tests, make sure that they
are complete and accurate.

. Make sure that `test161 run` is testing the same kernel that you are
submitting! This can happen if the root directory configured in your
`.test161.conf` file is different from where you are installing your kernels
and, as a result, hosts a stale kernel file. Check the file timestamps after
a `bmake install`.

. Examine the server logs to determine what went wrong and use that to focus
your local testing.

=== Differences Between the Local and Remote Testing Environments

One of the design goals of `test161` is to make local evaluation as accurate
as possible. However, there are some differences between your local test
environment and the remote one.

Specifically, before performing remote testing `test161` applies an _overlay_
to your kernel which removes some files and replaces the contents of others.
For example, we overwrite all of your ``Makefiles``s and anything else that
we have to interpret or run to make sure that you don't try to damage our
server. We also overwrite all of the tests in `kern/test` with trusted code
to ensure that your kernel is running our tests and that you didn't rewire
the menu to try and trick the testing suite footnote:[We have a few other
tricks up our sleeve here, so I wouldn't bother trying to flummox the remote
grader. Doing the assignment is probably easier.].

=== Cheating Detection

Finally, note that each repository submitted to the
https://test161.ops-class.org[`test161.ops-class.org`] server will be checked
in its entirely for plagiarism: *every file, and every commit*, not limited
to submissions. Any evidence of plagiarism will be forwarded to the relevant
course staff and plagiarized assignments will be removed from the `test161`
results.

== Writing `test161` Tests

[.lead]
`test161` is designed to allow you to test your kernel using both the tests
we have provided and new tests that you may write for each assignment.

Below we describe how to create and run your own `test161` scripts. But
first, we describe the three key components of the `test161` configuration
directory: tests, commands, and targets.

=== Tests

The main `test161` configuration object is a test, which are stored in files
with a `.t` extension footnote:[In homage to the original `test161` tool that
David wrote years ago that also used a `.t` extension.]. Here is an example
from `test161/synch/sem1.t`:

[source,role='noautohighlight']
----
---
name: "Semaphore Test"
description:
  Tests core semaphore logic through cycling signaling.
tags: [synch, semaphores]
depends: [boot]
sys161:
  cpus: 32
---
sem1
----

==== Front matter

The test consist of two parts. The header in between the first and second
`---` is http://yaml.org[YAML] front matter that provides test metadata. Here
it provides the name and a description of the test, includes the test in the
`synch` and `semaphores` tags, indicates that the test depends on the `boot`
test group, and configures `sys161` to run the test with 32 cores.

We will eventually provide more detail about test configuration options on
the https://github.com/ops-class/test161[GitHub page], but for now you can
get a sense for the options by reading other test files and looking at the
https://github.com/ops-class/test161#default-settings[`test161` defaults].
About the only commonly useful option not used by `sem1.t` is a `ram` option
for `sys161`.

==== Test inputs

After the front matter comes the test itself. `test161` tests can be
considered series of inputs to the `sys161` simulator, plus a bit of
https://github.com/ops-class/test161#testfile-syntactic-sugar[syntactic
sugar]. For example, in this case note that we did not need to explicitly
shut the kernel down: `sem1` expands automatically to `sem1; q`.

This is particularly useful when running commands from the shell. `test161`
provides a `$` prefix indicating that a command should be run from the shell,
and knows how to start and exit the shell as appropriate. So this single
command:

[source,role='noautohighlight']
----
$ /bin/true
----

expands to:

[source,role='noautohighlight']
----
s
/bin/true
exit
q
----

==== Groups of tests

`test161` allows you to group tests together using tags. For example, the
`sem1.t` test above is part of both the `semaphores` group (by itself) and
the `synch` group with a bunch of other tests, including `rwt{1-4}`,
`cvt{1-5}`, etc. Tags can be used both as arguments to `test161 run`:

[source,bash]
----
test161 run synch
----

and as dependencies to other tests. As shown above, the `sem1.t` test depends
on the `boot` group which currently consists only of `test161/boot.t`. Here
is another example from `cvt1.t`:

[source,role='noautohighlight']
----
---
name: "CV Test 1"
description:
  Tests core CV functionality through cyclic waiting.
tags: [synch, cvs]
depends: [boot, semaphores, locks]
sys161:
  cpus: 32
---
cvt1
----

Note that `cvt1.t` depends on `boot`, `locks` (since CVs require working
locks), and `semaphores` (since the test uses semaphores to shut down
cleanly).

=== Identifying single tests

Single tests can also be passed to `test161 run` or used as dependencies.
Single tests are identified by the relative path to the test file from the
`test161` configuration directory. For example, to run `boot.t` you would run
`test161 run boot.t`, and to run the `sem1.t` located in
`test161/synch/sem1.t` you would run `test161 run synch/sem1.t`.

Dependencies use the same syntax, _regardless of where the file that is
expressing the dependency is located_. For example, in `synch/cvt2.1.` we
could use `depends: [boot.t]`, or `depends: [synch/lt1.t]`.

=== Commands

`test161` tests consist of a series of _commands_ that are actually executed
by the running OS/161 kernel or shell. To process the output of a test,
`test161` needs to know what it should expect each test to do and what
constitutes success and failure. For example, some of our stability tests
intentionally create a panic, and in other cases tests may intentionally
hang: like `/testbin/forkbomb` for link:/asst/2/[ASST2].

`test161` reads this information from all files with `.tc` extensions in the
`commands` subdirectory. Files in that directory are again in
http://yaml.org[YAML] syntax and can be processed in any order. Here is a
snippet from `commands/

[source,role='noautohighlight']
----
templates:
  - name: sem1
  - name: lt1
	...
  - name: lt2
    panics: yes
    output:
      - text: "lt2: Should panic..."
----

Each commands file should define a single `templates` object consisting of an
array of output templates. Each names a single command, such as `sem1`, and
describes the output. By default, for tests that are only listed in a `.tc`
file `test161` will expect that output `<command name>: SUCCESS` indicates
success and the absence of this string indicates failure. Note that commands
must be named in a command file for this default to apply. Some commands,
like `q` and `exit`, do not succeed or fail--as long as they do not panic,
which `test161` monitors separately. So they are omitted from the `.tc` file.

// TODO: Beef up once we have ASST2 stuff.

The commands file can also indicate more about the expected output. For
example, the entry above for `lt2` indicates that it should panic on success
and print `lt2: Should panic` before panicking.

=== Targets

Tests and commands allow `test161` to run test scripts to evaluate your
OS/161 kernel. However, grading assignments requires one additional
components: _targets_.

Target files have a `.tt` extension and live in the `targets` subdirectory.
Each target configures a set of tests to run and their point values as well
as the kernel configuration and overlay used to build your kernel for that
specific target. Here is an example again drawn from link:/asst/1/[ASST1]:

[source,role='noautohighlight']
----
name: asst1
version: 1
points: 50
type: asst
kconfig: ASST1
tests:
  - id: synch/lt1.t
    points: 8
  - id: synch/lt2.t
    points: 1
  - id: synch/lt3.t
    points: 1
...
----

// TODO: Beef up performance targets once we have some.

Format is again, http://yaml.org[YAML]. This target tells `test161` to use
the `ASST1` kernel configuration file, that there should be 50 total points
included in all of the tests, and that this is a assignment-type
configuration. We will also eventually distribute performance targets
allowing you to race your OS/161 kernel against other students.

// TODO: Partial credit.

After the configuration each target includes a lists of tests to run,
identified using the single-test format described above. It also maps test
success output to points, and includes flexible ways to give partial credit
for tests and commands that support partial credit.
