---
title: "<code>ops-class.org</code> Toolchain"
description: >
  Overview of ops-class.org toolchain components, versions, and installation
  instructions.
omitTop: true
priority: 0.8
changefreq: monthly
spelling_exceptions:
  - LTS
  - Trusty Tahr
---
[.lead]
{ops-class} assignments require a specific toolchain. This page documents the
current versions of toolchain components.

'''

== OS/161

{os161} is maintained by http://www.hcs.harvard.edu/~dholland/[David Holland]
at Harvard University. We maintain a https://github.com/ops-class/os161[fork
of OS/161 on GitHub] that includes many {ops-class}-specific changes,
particularly related to testing automation using {test161}.

=== Current Version

https://github.com/ops-class/os161/tree/master[2.0.1]
based on http://os161.eecs.harvard.edu/download/[upstream version 2.0.1].
(Latest upstream is 2.0.2. We will incorporate these changes in Summer 2016.)

=== Installation

Clone our https://github.com/ops-class/os161[GitHub repository]. Note that
this sets the Git remote name to `staff` so that you can use `origin` for your
own private repository where you store your changes.

[source,bash]
----
git clone https://github.com/ops-class/os161 -o staff
----

=== Upgrading

Pull and merge upstream changes from our
https://github.com/ops-class/os161[GitHub repository]. Note that this depends
on having our OS/161 GitHub repository named `staff` rather than `origin`, as
described above. You will also need to inspect the output of `git pull` and
fix any merge conflicts that may result.

[source,bash]
----
git pull staff master
----

'''

[[vagrant]]
== Vagrant Virtual Machine

We maintain a https://github.com/ops-class/vagrant[Vagrant configuration]
based on http://releases.ubuntu.com/14.04/[Ubuntu 14.04 LTS "Trusty Tahr"]
that simplifies the process of installing the rest of the toolchain:
including `sys161`, the OS/161 cross-compilers, and `test161`. *This is the
recommended way to install the rest of the toolchain.*

=== Current Version

https://github.com/ops-class/vagrant/tree/v1.1[1.1] is the current version.

=== Installation

https://www.vagrantup.com/[Install Vagrant]. Then:

[source,bash]
----
git clone https://github.com/ops-class/vagrant
cd vagrant && vagrant up
----

If you are having trouble, please look at the
https://github.com/ops-class/vagrant/blob/master/README.adoc[README]. There
are some known issues on Windows hosts.

=== Upgrading

Upgrading the toolchain from inside the virtual machine is simple:

[source,bash]
----
[trinity@zion:~] $ sudo apt-get update ; sudo apt-get upgrade
----

Upgrading the virtual machine itself can be done by updating the
`Vagrantfile` and provisioning scripts via `git pull` and then forcing
Vagrant to reprovision the VM:

[source,bash]
----
vagrant halt
git pull
vagrant up --provision
----

It may be easier to simply destroy the old VM and create a new one. *But be
sure to preserve your OS/161 sources!*

'''

[[ppa]]
== {ops-class} Launchpad PPA

The {ops-class} {ppa} includes all toolchain components packaged for Ubuntu
14.04 "Trusty Tahr". If you 14.04 installed, you can install these packages
directly. If you are using a later Ubuntu release, the `trusty` packages will
probably work. If you are using an earlier Ubuntu release, you should upgrade.
If you need to install Ubuntu and don't want to run it on bare metal, try our
link:#vagrant[Vagrant virtual machine].

=== Installation

Our {ppa} makes things very simple:

[source,bash]
----
sudo add-apt-repository ppa:geoffrey-challen/os161-toolchain
sudo apt-get update ; sudo apt-get install os161-toolchain
----

=== Upgrading

Upgrading is also easy:

[source,bash]
----
sudo apt-get update ; sudo apt-get install os161-toolchain
----

== `test161` Client

{test161} is our OS/161 distributed automated grading and testing tool. It is
maintained by https://blue.cse.buffalo.edu/people/shaseley[Scott Haseley].
Sources are available on https://github.com/ops-class/test161[GitHub] and bug
fixes and improvements via pull requests are welcome.

=== Current Version

https://github.com/ops-class/test161/tree/v1.2.2[1.2.2] is the current version.

=== Installation

If you are using our link:#ppa[PPA], then you already have `test161`. If you
are installing from source, once you have https://golang.org[Go] installed,
the following command will install {test161} into your `$GOPATH`:

[source,bash]
----
go get -u github.com/ops-class/test161/test161
----

=== Upgrading

If you are using our link:#ppa[PPA], then follow the upgrade instructions
above. If you installed from source:

[source,bash]
----
go get -u github.com/ops-class/test161/test161
----

'''

== System/161

{system161} is also maintained by http://www.hcs.harvard.edu/~dholland/[David
Holland] at Harvard University. We maintain our own
https://github.com/ops-class/sys161[GitHub `sys161` repository] for the
purpose of packaging `sys161` for our {ppa}. We have also made some
contributions to `sys161` in version 2.0.6 and 2.0.7 related to {test161}
automation and statistics control.

=== Current Version

{ppa-link}[2.0.8] which is identical to
http://os161.eecs.harvard.edu/download/[upstream version 2.0.8].

=== Installation

If you are using our link:#ppa[PPA], then you already have `sys161`. You can
also try http://os161.eecs.harvard.edu/resources/setup.html[installing from
source] footnote:[Good luck!].

=== Upgrading

If you are using our link:#ppa[PPA], then follow the upgrade instructions
above. If you installed from source, reinstall from source.

'''

== OS/161 Cross Compilers

{os161} requires a set of patched cross compilers which are also (surprise
surprise) maintained by http://www.hcs.harvard.edu/~dholland/[David Holland]
at Harvard University. We have packaged these for our link:#ppa[PPA].

=== Current Version

Identical to the latest versions shown
http://os161.eecs.harvard.edu/download/[here].

=== Installation

If you are using our link:#ppa[PPA], then you already have the OS/161
toolchain. You can also try
http://os161.eecs.harvard.edu/resources/setup.html[installing from source].

=== Upgrading

If you are using our link:#ppa[PPA], then follow the upgrade instructions
above. If you installed from source, reinstall from source.
